version: '3.8'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample6
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}